// <auto-generated />
using System;
using Food.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Food.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Food.Entity.About", b =>
                {
                    b.Property<int>("about_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("about_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("about_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("about_Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("about_id");

                    b.ToTable("About");

                    b.HasData(
                        new
                        {
                            about_id = 1,
                            about_Description = "The Big Oxmox advised her not to do so, because there were thousands of bad Commas, wild Question Marks and devious Semikoli, but the Little Blind Text didn’t listen. She packed her seven versalia, put her initial into the belt and made herself on the way. \n \n When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove,the headline of Alphabet Village and the subline of her own road,the Line Lane.Pityful a rethoric question ran over her cheek,then she continued her way.",
                            about_Title = "Footwear the leading eCommerce Store around the Globe",
                            about_Url = "https://www.youtube.com/watch?v=F1vcruph8JA"
                        });
                });

            modelBuilder.Entity("Food.Entity.Bills", b =>
                {
                    b.Property<string>("bill_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("bill_Cancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("bill_Confirmation")
                        .HasColumnType("bit");

                    b.Property<DateTime>("bill_DatetimeOrder")
                        .HasColumnType("datetime2");

                    b.Property<bool>("bill_Delivered")
                        .HasColumnType("bit");

                    b.Property<bool>("bill_Delivering")
                        .HasColumnType("bit");

                    b.Property<int>("bill_Discount")
                        .HasColumnType("int");

                    b.Property<bool>("bill_HideStatus")
                        .HasColumnType("bit");

                    b.Property<string>("bill_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("bill_PaidTotal")
                        .HasColumnType("int");

                    b.Property<string>("bill_PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductColorlist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductIdlist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductNamelist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductPricelist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductSizelist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_Quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("bill_Shipping")
                        .HasColumnType("int");

                    b.Property<string>("bill_UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("bill_WaitForConfirmation")
                        .HasColumnType("bit");

                    b.Property<bool>("bill_WaitPickup")
                        .HasColumnType("bit");

                    b.HasKey("bill_Id");

                    b.HasIndex("bill_UserId");

                    b.ToTable("Bills");

                    b.HasData(
                        new
                        {
                            bill_Id = "D269BF93-A5E2-4C4A-8146-9967DDE80D30",
                            bill_Cancelled = false,
                            bill_Confirmation = true,
                            bill_DatetimeOrder = new DateTime(2023, 4, 1, 15, 6, 21, 412, DateTimeKind.Local).AddTicks(5040),
                            bill_Delivered = false,
                            bill_Delivering = false,
                            bill_Discount = 0,
                            bill_HideStatus = false,
                            bill_Note = "",
                            bill_PaidTotal = 2000,
                            bill_PaymentMethod = "Check Payment",
                            bill_ProductIdlist = "1|2|3|4",
                            bill_ProductNamelist = "product 1|product 2| product 3| product 4|",
                            bill_ProductPricelist = "550|450|350|640|",
                            bill_Quantity = "1|1|2|1|",
                            bill_Shipping = 10,
                            bill_UserId = "f49e4348-718f-43e3-b1f6-6dc89c5Bb5ff",
                            bill_WaitForConfirmation = false,
                            bill_WaitPickup = false
                        });
                });

            modelBuilder.Entity("Food.Entity.Cart", b =>
                {
                    b.Property<string>("cart_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("cart_UserID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("cart_Id");

                    b.HasIndex("cart_UserID");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            cart_Id = "72309286-ECBB-4D20-AD95-2819D31E3400",
                            cart_UserID = "f49e4348-718f-43e3-b1f6-6dc89c5Bb5ff"
                        },
                        new
                        {
                            cart_Id = "D355458F-1DD3-4834-AA28-6DA34B6357FF",
                            cart_UserID = "DE544998-A3CC-4E12-ABB4-0642E57BD222"
                        });
                });

            modelBuilder.Entity("Food.Entity.CartsDevice", b =>
                {
                    b.Property<string>("cartd_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("cartd_DeviceId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("cartd_Id");

                    b.HasIndex("cartd_DeviceId");

                    b.ToTable("CartsDevice");
                });

            modelBuilder.Entity("Food.Entity.Categories", b =>
                {
                    b.Property<string>("cg_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("cg_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cg_Sale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cg_Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cg_Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            cg_Id = "3b26a7c9-0162-4e24-98dc-e99a5fe145bd",
                            cg_Name = "Dry food",
                            cg_Sale = "",
                            cg_Type = ""
                        },
                        new
                        {
                            cg_Id = "f5952fd8-549e-4723-afbc-86ebc1c90b44",
                            cg_Name = "Food",
                            cg_Sale = "",
                            cg_Type = ""
                        },
                        new
                        {
                            cg_Id = "8b878d9e-edca-4174-adfe-e44571c84f08",
                            cg_Name = "Drink",
                            cg_Sale = "",
                            cg_Type = ""
                        },
                        new
                        {
                            cg_Id = "23fbc3f1-8035-45c9-aa2a-01848fce9ca9",
                            cg_Name = "Banhmi",
                            cg_Sale = "",
                            cg_Type = ""
                        },
                        new
                        {
                            cg_Id = "21c3632b-cd11-4089-a734-654798d32f11",
                            cg_Name = "Snack",
                            cg_Sale = "",
                            cg_Type = ""
                        });
                });

            modelBuilder.Entity("Food.Entity.ContactSystem", b =>
                {
                    b.Property<string>("Contact_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Contact_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Contact_Id");

                    b.ToTable("ContactSystems");

                    b.HasData(
                        new
                        {
                            Contact_Id = "3ce01285-bfee-4b37-8059-e66f71579c6d",
                            Contact_Address = "Huntsville, AL 35813, USA",
                            Contact_Description = "Prof Lord John Krebs provides a brief history of human food, from our remote ancestors 3 million years ago to the present day. By looking at the four great transitions in human food - cooking, agriculture, processing, and preservation - he considers a variety of questions, including why people like some kinds of foods and not others; how your senses contribute to flavor; the role of genetics in our likes and dislikes; and the differences in learning and culture around the world.",
                            Contact_Email = "support@foodshop.com ",
                            Contact_Phone = "021.343.7575"
                        });
                });

            modelBuilder.Entity("Food.Entity.ContactUsers", b =>
                {
                    b.Property<string>("cu_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("cu_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cu_Id");

                    b.ToTable("ContactUsers");

                    b.HasData(
                        new
                        {
                            cu_Id = "d988499d-5e0f-4507-90e5-c29762a49f9b",
                            cu_Description = "Description",
                            cu_Email = "Email",
                            cu_FirstName = "FirstName",
                            cu_LastName = "LastName",
                            cu_Subject = "Subject"
                        });
                });

            modelBuilder.Entity("Food.Entity.Coupons", b =>
                {
                    b.Property<string>("couponId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("couponCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("couponPrice")
                        .HasColumnType("int");

                    b.HasKey("couponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            couponId = "ce74364b-cdf3-4900-859c-0eb1a7f1db8d",
                            couponCode = "code10",
                            couponPrice = 10
                        },
                        new
                        {
                            couponId = "8cbedce7-02bf-4f43-988a-7cfb37e99336",
                            couponCode = "code50",
                            couponPrice = 50
                        });
                });

            modelBuilder.Entity("Food.Entity.Device", b =>
                {
                    b.Property<string>("deviceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("deviceAddress1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceCompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("devicePhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("devicePostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceState")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("deviceId");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("Food.Entity.ProductInCart", b =>
                {
                    b.Property<string>("pic_CartId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pic_ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("pic_amount")
                        .HasColumnType("int");

                    b.Property<string>("pic_color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pic_size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pic_CartId", "pic_ProductId");

                    b.HasIndex("pic_ProductId");

                    b.ToTable("ProductInCart");
                });

            modelBuilder.Entity("Food.Entity.ProductInCartDevices", b =>
                {
                    b.Property<string>("picd_CartId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("picd_ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("picd_amount")
                        .HasColumnType("int");

                    b.Property<string>("picd_color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("picd_size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("picd_CartId", "picd_ProductId");

                    b.HasIndex("picd_ProductId");

                    b.ToTable("ProductInCartDevices");
                });

            modelBuilder.Entity("Food.Entity.Products", b =>
                {
                    b.Property<string>("pd_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.Property<string>("pd_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_Img1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_Img2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_Img3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_Img4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_NameImg1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_NameImg2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_NameImg3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_NameImg4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pd_Price")
                        .HasColumnType("int");

                    b.Property<int>("pd_Rate")
                        .HasColumnType("int");

                    b.Property<int>("pd_ReducePrice")
                        .HasColumnType("int");

                    b.Property<string>("pd_ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("pd_WaitForConfirmation")
                        .HasColumnType("bit");

                    b.HasKey("pd_Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            pd_Id = "7b1966a6-c328-4489-b380-acae90575ddb",
                            isDelete = false,
                            pd_Description = "BanhCanhCua",
                            pd_Img1 = "/images/item250x300/BanhCanhCua.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "BanhCanhCua",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "1b874aaf-0679-47fa-abba-d3f874f64514",
                            isDelete = false,
                            pd_Description = "BanhMi",
                            pd_Img1 = "/images/item250x300/BanhMi.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "BanhMi",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "4e2ffdff-7078-4454-a721-a941c7ec252d",
                            isDelete = false,
                            pd_Description = "banhtrangtron",
                            pd_Img1 = "/images/item250x300/banhtrangtron.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "banhtrangtron",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "765eec31-8af6-47bc-a84c-d864115a2e75",
                            isDelete = false,
                            pd_Description = "banhuotlongdalat",
                            pd_Img1 = "/images/item250x300/banhuotlongdalat.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "banhuotlongdalat",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "a9f30ba1-0ced-4d2c-9067-768a18cae760",
                            isDelete = false,
                            pd_Description = "BoKho",
                            pd_Img1 = "/images/item250x300/BoKho.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "BoKho",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "2637a2f8-2d5a-4253-99b9-afb941ec866b",
                            isDelete = false,
                            pd_Description = "bunbo",
                            pd_Img1 = "/images/item250x300/bunbo.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "bunbo",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "41b57dce-0887-4859-8570-7337cbb6b79a",
                            isDelete = false,
                            pd_Description = "bundaumamtom",
                            pd_Img1 = "/images/item250x300/bundaumamtom.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "bundaumamtom",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "025afe57-28d1-4e42-9bb1-fcf1168612c6",
                            isDelete = false,
                            pd_Description = "Bunxaochay",
                            pd_Img1 = "/images/item250x300/Bunxaochay.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "Bunxaochay",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "b8147a11-d1f1-44a9-bc7b-afb50c993422",
                            isDelete = false,
                            pd_Description = "cocosummer",
                            pd_Img1 = "/images/item250x300/cocosummer.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "cocosummer",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "91da00b1-99fe-4c9c-9baf-12834fcf6805",
                            isDelete = false,
                            pd_Description = "comboxao",
                            pd_Img1 = "/images/item250x300/comboxao.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "comboxao",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "8d3dee41-02de-4973-9f7c-abaa3062d6b8",
                            isDelete = false,
                            pd_Description = "comga",
                            pd_Img1 = "/images/item250x300/comga.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "comga",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "433b8333-d6f3-4238-b2ea-3f834ceb456e",
                            isDelete = false,
                            pd_Description = "comgadenhat",
                            pd_Img1 = "/images/item250x300/comgadenhat.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "comgadenhat",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "99d5ce11-7f58-4a05-aa72-97273e2fe0fa",
                            isDelete = false,
                            pd_Description = "denhatthitnuong",
                            pd_Img1 = "/images/item250x300/denhatthitnuong.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "denhatthitnuong",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "03d0ba8a-d078-4be4-8914-cb5bab3e9150",
                            isDelete = false,
                            pd_Description = "goicuon",
                            pd_Img1 = "/images/item250x300/goicuon.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "goicuon",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "b5c89b46-469c-4ddb-93b9-fbfa33241e6d",
                            isDelete = false,
                            pd_Description = "kfc",
                            pd_Img1 = "/images/item250x300/kfc.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "kfc",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "73de4849-8571-4b7f-8835-d896638652d7",
                            isDelete = false,
                            pd_Description = "KimBap",
                            pd_Img1 = "/images/item250x300/KimBap.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "KimBap",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "11fafc66-c1f8-41a5-b623-842522e04b79",
                            isDelete = false,
                            pd_Description = "loteria",
                            pd_Img1 = "/images/item250x300/loteria.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "loteria",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "a5317d16-fe74-4e2d-96fb-f5f898967dd0",
                            isDelete = false,
                            pd_Description = "mitronanvat",
                            pd_Img1 = "/images/item250x300/mitronanvat.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "mitronanvat",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "420fd529-ac6f-4cd6-8619-13ac63efd1d9",
                            isDelete = false,
                            pd_Description = "monngontrangbang",
                            pd_Img1 = "/images/item250x300/monngontrangbang.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "monngontrangbang",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "cc10067b-7603-4055-b40d-b32bf24caf20",
                            isDelete = false,
                            pd_Description = "ParisBaguete",
                            pd_Img1 = "/images/item250x300/ParisBaguete.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "ParisBaguete",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "a401bf26-d7c3-4c10-9ca4-24b73388c38a",
                            isDelete = false,
                            pd_Description = "pizza",
                            pd_Img1 = "/images/item250x300/pizza.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "pizza",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "3a963e2b-245e-4dc4-93fa-33f30525a04d",
                            isDelete = false,
                            pd_Description = "quanngontrangbang",
                            pd_Img1 = "/images/item250x300/quanngontrangbang.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "quanngontrangbang",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "5f99c2ce-f127-4c93-90cc-7121c46b9591",
                            isDelete = false,
                            pd_Description = "RauMaMix",
                            pd_Img1 = "/images/item250x300/RauMaMix.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "RauMaMix",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "381e57b9-08c1-485b-b4fc-650f6baee88d",
                            isDelete = false,
                            pd_Description = "Royaltea",
                            pd_Img1 = "/images/item250x300/Royaltea.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "Royaltea",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "e908d140-6e20-4a9e-921f-10f3d52acceb",
                            isDelete = false,
                            pd_Description = "Sanfulou",
                            pd_Img1 = "/images/item250x300/Sanfulou.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "Sanfulou",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "ec3d165b-21b4-4ee6-913f-3db39e6bc52d",
                            isDelete = false,
                            pd_Description = "stacbuk-cf",
                            pd_Img1 = "/images/item250x300/stacbuk-cf.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "stacbuk-cf",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "95908146-bff6-4ac6-9f8f-ad73c9f993a8",
                            isDelete = false,
                            pd_Description = "trasuanhalam",
                            pd_Img1 = "/images/item250x300/trasuanhalam.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "trasuanhalam",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "e1fd379f-e886-4c2b-8d3f-4b778d74c8f3",
                            isDelete = false,
                            pd_Description = "Xoixeoba3beo",
                            pd_Img1 = "/images/item250x300/Xoixeoba3beo.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "Xoixeoba3beo",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        });
                });

            modelBuilder.Entity("Food.Entity.ProductsInCategories", b =>
                {
                    b.Property<string>("pic_productId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pic_CategoriesId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("pic_productId", "pic_CategoriesId");

                    b.HasIndex("pic_CategoriesId");

                    b.ToTable("ProductsInCategories");

                    b.HasData(
                        new
                        {
                            pic_productId = "41b57dce-0887-4859-8570-7337cbb6b79a",
                            pic_CategoriesId = "3b26a7c9-0162-4e24-98dc-e99a5fe145bd"
                        },
                        new
                        {
                            pic_productId = "025afe57-28d1-4e42-9bb1-fcf1168612c6",
                            pic_CategoriesId = "3b26a7c9-0162-4e24-98dc-e99a5fe145bd"
                        },
                        new
                        {
                            pic_productId = "91da00b1-99fe-4c9c-9baf-12834fcf6805",
                            pic_CategoriesId = "3b26a7c9-0162-4e24-98dc-e99a5fe145bd"
                        },
                        new
                        {
                            pic_productId = "8d3dee41-02de-4973-9f7c-abaa3062d6b8",
                            pic_CategoriesId = "3b26a7c9-0162-4e24-98dc-e99a5fe145bd"
                        },
                        new
                        {
                            pic_productId = "433b8333-d6f3-4238-b2ea-3f834ceb456e",
                            pic_CategoriesId = "3b26a7c9-0162-4e24-98dc-e99a5fe145bd"
                        },
                        new
                        {
                            pic_productId = "99d5ce11-7f58-4a05-aa72-97273e2fe0fa",
                            pic_CategoriesId = "3b26a7c9-0162-4e24-98dc-e99a5fe145bd"
                        },
                        new
                        {
                            pic_productId = "03d0ba8a-d078-4be4-8914-cb5bab3e9150",
                            pic_CategoriesId = "3b26a7c9-0162-4e24-98dc-e99a5fe145bd"
                        },
                        new
                        {
                            pic_productId = "73de4849-8571-4b7f-8835-d896638652d7",
                            pic_CategoriesId = "3b26a7c9-0162-4e24-98dc-e99a5fe145bd"
                        },
                        new
                        {
                            pic_productId = "7b1966a6-c328-4489-b380-acae90575ddb",
                            pic_CategoriesId = "f5952fd8-549e-4723-afbc-86ebc1c90b44"
                        },
                        new
                        {
                            pic_productId = "765eec31-8af6-47bc-a84c-d864115a2e75",
                            pic_CategoriesId = "f5952fd8-549e-4723-afbc-86ebc1c90b44"
                        },
                        new
                        {
                            pic_productId = "a9f30ba1-0ced-4d2c-9067-768a18cae760",
                            pic_CategoriesId = "f5952fd8-549e-4723-afbc-86ebc1c90b44"
                        },
                        new
                        {
                            pic_productId = "2637a2f8-2d5a-4253-99b9-afb941ec866b",
                            pic_CategoriesId = "f5952fd8-549e-4723-afbc-86ebc1c90b44"
                        },
                        new
                        {
                            pic_productId = "420fd529-ac6f-4cd6-8619-13ac63efd1d9",
                            pic_CategoriesId = "f5952fd8-549e-4723-afbc-86ebc1c90b44"
                        },
                        new
                        {
                            pic_productId = "5f99c2ce-f127-4c93-90cc-7121c46b9591",
                            pic_CategoriesId = "8b878d9e-edca-4174-adfe-e44571c84f08"
                        },
                        new
                        {
                            pic_productId = "381e57b9-08c1-485b-b4fc-650f6baee88d",
                            pic_CategoriesId = "8b878d9e-edca-4174-adfe-e44571c84f08"
                        },
                        new
                        {
                            pic_productId = "ec3d165b-21b4-4ee6-913f-3db39e6bc52d",
                            pic_CategoriesId = "8b878d9e-edca-4174-adfe-e44571c84f08"
                        },
                        new
                        {
                            pic_productId = "95908146-bff6-4ac6-9f8f-ad73c9f993a8",
                            pic_CategoriesId = "8b878d9e-edca-4174-adfe-e44571c84f08"
                        },
                        new
                        {
                            pic_productId = "1b874aaf-0679-47fa-abba-d3f874f64514",
                            pic_CategoriesId = "23fbc3f1-8035-45c9-aa2a-01848fce9ca9"
                        },
                        new
                        {
                            pic_productId = "a5317d16-fe74-4e2d-96fb-f5f898967dd0",
                            pic_CategoriesId = "23fbc3f1-8035-45c9-aa2a-01848fce9ca9"
                        },
                        new
                        {
                            pic_productId = "4e2ffdff-7078-4454-a721-a941c7ec252d",
                            pic_CategoriesId = "21c3632b-cd11-4089-a734-654798d32f11"
                        },
                        new
                        {
                            pic_productId = "b8147a11-d1f1-44a9-bc7b-afb50c993422",
                            pic_CategoriesId = "21c3632b-cd11-4089-a734-654798d32f11"
                        },
                        new
                        {
                            pic_productId = "b5c89b46-469c-4ddb-93b9-fbfa33241e6d",
                            pic_CategoriesId = "21c3632b-cd11-4089-a734-654798d32f11"
                        },
                        new
                        {
                            pic_productId = "11fafc66-c1f8-41a5-b623-842522e04b79",
                            pic_CategoriesId = "21c3632b-cd11-4089-a734-654798d32f11"
                        },
                        new
                        {
                            pic_productId = "cc10067b-7603-4055-b40d-b32bf24caf20",
                            pic_CategoriesId = "21c3632b-cd11-4089-a734-654798d32f11"
                        },
                        new
                        {
                            pic_productId = "a401bf26-d7c3-4c10-9ca4-24b73388c38a",
                            pic_CategoriesId = "21c3632b-cd11-4089-a734-654798d32f11"
                        },
                        new
                        {
                            pic_productId = "3a963e2b-245e-4dc4-93fa-33f30525a04d",
                            pic_CategoriesId = "21c3632b-cd11-4089-a734-654798d32f11"
                        },
                        new
                        {
                            pic_productId = "e908d140-6e20-4a9e-921f-10f3d52acceb",
                            pic_CategoriesId = "21c3632b-cd11-4089-a734-654798d32f11"
                        },
                        new
                        {
                            pic_productId = "e1fd379f-e886-4c2b-8d3f-4b778d74c8f3",
                            pic_CategoriesId = "21c3632b-cd11-4089-a734-654798d32f11"
                        });
                });

            modelBuilder.Entity("Food.Entity.ReviewInproduct", b =>
                {
                    b.Property<string>("rip_ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("rip_ReviewId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("rip_ProductId", "rip_ReviewId");

                    b.HasIndex("rip_ReviewId");

                    b.ToTable("ReviewInproduct");

                    b.HasData(
                        new
                        {
                            rip_ProductId = "7b1966a6-c328-4489-b380-acae90575ddb",
                            rip_ReviewId = "EEBA6608-AB75-4E83-909F-604B1A06F16C"
                        },
                        new
                        {
                            rip_ProductId = "7b1966a6-c328-4489-b380-acae90575ddb",
                            rip_ReviewId = "9EED8607-D2BB-45EE-AEE3-C59D858A7F97"
                        },
                        new
                        {
                            rip_ProductId = "7b1966a6-c328-4489-b380-acae90575ddb",
                            rip_ReviewId = "C2A543C2-B1E2-4DC5-A131-9137E4673FA6"
                        });
                });

            modelBuilder.Entity("Food.Entity.Reviews", b =>
                {
                    b.Property<string>("review_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("review_Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("review_HideStatus")
                        .HasColumnType("bit");

                    b.Property<string>("review_ReviewType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("review_UploadTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("review_UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("review_id");

                    b.HasIndex("review_UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            review_id = "EEBA6608-AB75-4E83-909F-604B1A06F16C",
                            review_Comment = "Good1",
                            review_HideStatus = false,
                            review_ReviewType = "Review",
                            review_UploadTime = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            review_UserId = "DE544998-A3CC-4E12-ABB4-0642E57BD222"
                        },
                        new
                        {
                            review_id = "9EED8607-D2BB-45EE-AEE3-C59D858A7F97",
                            review_Comment = "Good2",
                            review_HideStatus = false,
                            review_ReviewType = "Review",
                            review_UploadTime = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            review_UserId = "f49e4348-718f-43e3-b1f6-6dc89c5Bb5ff"
                        },
                        new
                        {
                            review_id = "C2A543C2-B1E2-4DC5-A131-9137E4673FA6",
                            review_Comment = "Good3",
                            review_HideStatus = false,
                            review_ReviewType = "Review",
                            review_UploadTime = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            review_UserId = "DE544998-A3CC-4E12-ABB4-0642E57BD222"
                        });
                });

            modelBuilder.Entity("Food.Entity.Shipping", b =>
                {
                    b.Property<string>("ship_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ship_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ship_Price")
                        .HasColumnType("int");

                    b.HasKey("ship_Id");

                    b.ToTable("Shipping");

                    b.HasData(
                        new
                        {
                            ship_Id = "7CF94A7D-9239-446E-A404-086518F84652",
                            ship_Name = "Ship",
                            ship_Price = 5
                        });
                });

            modelBuilder.Entity("Food.Entity.SubReview", b =>
                {
                    b.Property<string>("subReview_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("subReview_Commnet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("subReview_DateCommnet")
                        .HasColumnType("datetime2");

                    b.Property<bool>("subReview_HideStatus")
                        .HasColumnType("bit");

                    b.Property<string>("subReview_UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("subreview_SubReviewType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("subReview_Id");

                    b.HasIndex("subReview_UserId");

                    b.ToTable("SubReview");

                    b.HasData(
                        new
                        {
                            subReview_Id = "daf7daa4-d1ab-4ee4-8b0f-7c7224626d71",
                            subReview_Commnet = "subreview 1",
                            subReview_DateCommnet = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            subReview_HideStatus = false,
                            subReview_UserId = "DE544998-A3CC-4E12-ABB4-0642E57BD222",
                            subreview_SubReviewType = "SubReview"
                        },
                        new
                        {
                            subReview_Id = "da81b5c6-5540-4d55-bd83-75f226a09f18",
                            subReview_Commnet = "subreview 3",
                            subReview_DateCommnet = new DateTime(2020, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            subReview_HideStatus = false,
                            subReview_UserId = "f49e4348-718f-43e3-b1f6-6dc89c5Bb5ff",
                            subreview_SubReviewType = "SubReview"
                        },
                        new
                        {
                            subReview_Id = "d499cf82-8dc0-4163-93ee-ba6f30e1dbb3",
                            subReview_Commnet = "subreview 3",
                            subReview_DateCommnet = new DateTime(2020, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            subReview_HideStatus = false,
                            subReview_UserId = "DE544998-A3CC-4E12-ABB4-0642E57BD222",
                            subreview_SubReviewType = "SubReview"
                        });
                });

            modelBuilder.Entity("Food.Entity.SubReviewInReview", b =>
                {
                    b.Property<string>("SRiR_ReviewId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SRiR_SubReviewId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SRiR_ReviewId", "SRiR_SubReviewId");

                    b.HasIndex("SRiR_SubReviewId");

                    b.ToTable("SubReviewInReview");

                    b.HasData(
                        new
                        {
                            SRiR_ReviewId = "EEBA6608-AB75-4E83-909F-604B1A06F16C",
                            SRiR_SubReviewId = "daf7daa4-d1ab-4ee4-8b0f-7c7224626d71"
                        },
                        new
                        {
                            SRiR_ReviewId = "EEBA6608-AB75-4E83-909F-604B1A06F16C",
                            SRiR_SubReviewId = "da81b5c6-5540-4d55-bd83-75f226a09f18"
                        },
                        new
                        {
                            SRiR_ReviewId = "9EED8607-D2BB-45EE-AEE3-C59D858A7F97",
                            SRiR_SubReviewId = "d499cf82-8dc0-4163-93ee-ba6f30e1dbb3"
                        });
                });

            modelBuilder.Entity("Food.Entity.SubscribeEmail", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubscribeEmail");
                });

            modelBuilder.Entity("Food.Models.UserInRoleModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("UserInRoleModel");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "f49e4348-718f-43e3-b1f6-6dc89c5Bb5ff",
                            RoleId = "f49e4348-718f-43e3-b1f6-6dc89c5Bb4fd"
                        },
                        new
                        {
                            UserId = "DE544998-A3CC-4E12-ABB4-0642E57BD222",
                            RoleId = "360E601E-92F2-4F08-832B-604A21293258"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Food.Entity.AppRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.ToTable("Roles");

                    b.HasDiscriminator().HasValue("AppRole");

                    b.HasData(
                        new
                        {
                            Id = "f49e4348-718f-43e3-b1f6-6dc89c5Bb4fd",
                            ConcurrencyStamp = "7fd5b6a1-1506-467b-8f23-243fd943bd41",
                            Name = "Staff",
                            NormalizedName = "staff",
                            Description = "Staff",
                            isDelete = false
                        },
                        new
                        {
                            Id = "360E601E-92F2-4F08-832B-604A21293258",
                            ConcurrencyStamp = "f34380fb-01f6-4a89-9fb0-7a1d3bce6349",
                            Name = "Admin",
                            NormalizedName = "admin",
                            Description = "Admin",
                            isDelete = false
                        });
                });

            modelBuilder.Entity("Food.Entity.AppUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_State")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("AppUser");

                    b.HasData(
                        new
                        {
                            Id = "DE544998-A3CC-4E12-ABB4-0642E57BD222",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1335ddcb-6016-41b3-a68d-52d4e099d337",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEApI7hFFwJkzVEwciPBARhpfEPWPykkJinOxQRRIYKPyPAmEXkX9XwPazQPpGpbH/Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e2e0b968-0542-46ec-982a-f7ff7aa6607a",
                            TwoFactorEnabled = false,
                            UserName = "Admin",
                            DoB = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "admin",
                            LastName = "admin"
                        },
                        new
                        {
                            Id = "f49e4348-718f-43e3-b1f6-6dc89c5Bb5ff",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f5a5cfd3-c92f-46bf-98b5-a7a064a1472c",
                            Email = "staff@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF@GMAIL.COM",
                            NormalizedUserName = "STAFF@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEMTlER3a/QLNTNWTS2nuI4JfMJzJgnzXBD2rahPdEbrdr7KF41iMs6Py4ybdHQE3Cw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ec744e73-01d0-4c25-8344-fb47c45ab459",
                            TwoFactorEnabled = false,
                            UserName = "Staff",
                            DoB = new DateTime(2020, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "staff",
                            LastName = "staff"
                        });
                });

            modelBuilder.Entity("Food.Entity.Bills", b =>
                {
                    b.HasOne("Food.Entity.AppUser", "AppUserB")
                        .WithMany("BillsAU")
                        .HasForeignKey("bill_UserId");

                    b.Navigation("AppUserB");
                });

            modelBuilder.Entity("Food.Entity.Cart", b =>
                {
                    b.HasOne("Food.Entity.AppUser", "AppUserC")
                        .WithMany("CartU")
                        .HasForeignKey("cart_UserID");

                    b.Navigation("AppUserC");
                });

            modelBuilder.Entity("Food.Entity.CartsDevice", b =>
                {
                    b.HasOne("Food.Entity.Device", "DeviceCD")
                        .WithMany("CartsDeviceD")
                        .HasForeignKey("cartd_DeviceId");

                    b.Navigation("DeviceCD");
                });

            modelBuilder.Entity("Food.Entity.ProductInCart", b =>
                {
                    b.HasOne("Food.Entity.Cart", "CartPICart")
                        .WithMany("ProductInCartC")
                        .HasForeignKey("pic_CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Food.Entity.Products", "ProductsPICart")
                        .WithMany("ProductInCartP")
                        .HasForeignKey("pic_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartPICart");

                    b.Navigation("ProductsPICart");
                });

            modelBuilder.Entity("Food.Entity.ProductInCartDevices", b =>
                {
                    b.HasOne("Food.Entity.CartsDevice", "CartsDevicePICD")
                        .WithMany("ProductInCartDevicesCD")
                        .HasForeignKey("picd_CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Food.Entity.Products", "ProductsPICD")
                        .WithMany("ProductInCartDevicesP")
                        .HasForeignKey("picd_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartsDevicePICD");

                    b.Navigation("ProductsPICD");
                });

            modelBuilder.Entity("Food.Entity.ProductsInCategories", b =>
                {
                    b.HasOne("Food.Entity.Categories", "CategoriesPIC")
                        .WithMany("ProductsInCategoriesC")
                        .HasForeignKey("pic_CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Food.Entity.Products", "ProductsPIC")
                        .WithMany("ProductsInCategoriesP")
                        .HasForeignKey("pic_productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriesPIC");

                    b.Navigation("ProductsPIC");
                });

            modelBuilder.Entity("Food.Entity.ReviewInproduct", b =>
                {
                    b.HasOne("Food.Entity.Products", "ProductsRIP")
                        .WithMany("ReviewInproductP")
                        .HasForeignKey("rip_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Food.Entity.Reviews", "ReviewsRIP")
                        .WithMany("ReviewInproductR")
                        .HasForeignKey("rip_ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductsRIP");

                    b.Navigation("ReviewsRIP");
                });

            modelBuilder.Entity("Food.Entity.Reviews", b =>
                {
                    b.HasOne("Food.Entity.AppUser", "AppUserR")
                        .WithMany("ReviewsU")
                        .HasForeignKey("review_UserId");

                    b.Navigation("AppUserR");
                });

            modelBuilder.Entity("Food.Entity.SubReview", b =>
                {
                    b.HasOne("Food.Entity.AppUser", "AppUserSR")
                        .WithMany("SubReviewSR")
                        .HasForeignKey("subReview_UserId");

                    b.Navigation("AppUserSR");
                });

            modelBuilder.Entity("Food.Entity.SubReviewInReview", b =>
                {
                    b.HasOne("Food.Entity.Reviews", "Reviews")
                        .WithMany("SubReviewInReview")
                        .HasForeignKey("SRiR_ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Food.Entity.SubReview", "SubReview")
                        .WithMany("SubReviewInReview")
                        .HasForeignKey("SRiR_SubReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviews");

                    b.Navigation("SubReview");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Food.Entity.Cart", b =>
                {
                    b.Navigation("ProductInCartC");
                });

            modelBuilder.Entity("Food.Entity.CartsDevice", b =>
                {
                    b.Navigation("ProductInCartDevicesCD");
                });

            modelBuilder.Entity("Food.Entity.Categories", b =>
                {
                    b.Navigation("ProductsInCategoriesC");
                });

            modelBuilder.Entity("Food.Entity.Device", b =>
                {
                    b.Navigation("CartsDeviceD");
                });

            modelBuilder.Entity("Food.Entity.Products", b =>
                {
                    b.Navigation("ProductInCartDevicesP");

                    b.Navigation("ProductInCartP");

                    b.Navigation("ProductsInCategoriesP");

                    b.Navigation("ReviewInproductP");
                });

            modelBuilder.Entity("Food.Entity.Reviews", b =>
                {
                    b.Navigation("ReviewInproductR");

                    b.Navigation("SubReviewInReview");
                });

            modelBuilder.Entity("Food.Entity.SubReview", b =>
                {
                    b.Navigation("SubReviewInReview");
                });

            modelBuilder.Entity("Food.Entity.AppUser", b =>
                {
                    b.Navigation("BillsAU");

                    b.Navigation("CartU");

                    b.Navigation("ReviewsU");

                    b.Navigation("SubReviewSR");
                });
#pragma warning restore 612, 618
        }
    }
}
